export const products = [
  {
    id: 1,
    title: "Maggi",
    description: "I love Maggi realy oo yues  Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: "25",
    img: "images/maggi.jpg",
    quantity: 1,
  },
  {
    id: 2,
    title: "Corn",
    description: "I love corn realy oo yues  Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: "20",
    img: "images/corn.jpg",
    quantity: 1,
  },
  {
    id: 3,
    title: "Samosa",
    description: "I love samosa realy oo yues  Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: "15",
    img: "images/samosa.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "Allu pakoda",
    description: "I love allu pakoda realy oo yues  Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: "10",
    img: "images/allupakoida.jpg",
    quantity: 1,
  },
  {
    id: 5,
    title: "Momo",
    description: "I love momo realy oo yues  Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: "20",
    img: "images/momo.jpg",
    quantity: 1,
  },
  {
    id: 6,
    title: "Pizza",
    description: "I love pizza realy oo yues  Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: "60",
    img: "images/pizza.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "Chola",
    description: "I love Chola realy oo yues  Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: "15",
    img: "images/chola.jpg",
    quantity: 1,
  },
];
